### ISSUE TITLE
error

### ISSUE THREAD

**Issue by fann22** [corazonthedev/Google-form-parser#1]
```
3467 selenium/Google-form-parser-main  » python *.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.12/tkinter/__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/data/user/0/com.termux/files/home/selenium/Google-form-parser-main/google_form_parser.py", line 57, in <lambda>
    submit_button = tk.Button(root, text="Submit", command= lambda: self.save_link(entry_user_email,entry_user_password,entry_user_link))
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.termux/files/home/selenium/Google-form-parser-main/google_form_parser.py", line 70, in save_link
    TestParser.check_account_link(sb,user_link,user_email,user_password)
  File "/data/user/0/com.termux/files/home/selenium/Google-form-parser-main/google_form_parser.py", line 76, in check_account_link
    self.click('div[id="identifierNext"]') #next
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/seleniumbase/fixtures/base_case.py", line 410, in click
    element = page_actions.wait_for_element_visible(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/seleniumbase/fixtures/page_actions.py", line 494, in wait_for_element_visible
    timeout_exception(NoSuchElementException, message)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/seleniumbase/fixtures/page_actions.py", line 252, in timeout_exception
    raise exc(msg)
seleniumbase.common.exceptions.NoSuchElementException: Message:
 Element {div[id="identifierNext"]} was not present after 7 seconds!
```

any idea how to fix this?

**Comment by corazonthedev** [comment]
probably parser is trying to parse before page load, check the latest.log and set headless=False to see the process clearly

**Comment by corazonthedev** [comment]
yes, after multiple tries google directs you to captcha, you can change your gmail account or install auto-captcha extension in google extensions

**Comment by fann22** [comment]
> yes, after multiple tries google directs you to captcha, you can change your gmail account or install auto-captcha extension in google extension

i successfully implement captcha input manually but error keeps happening
![error_screenshot](https://github.com/user-attachments/assets/c294d6dd-949f-41ea-9e35-887a855e9756)

```
3483 home/selenium  » python main.py
enter captcha here (if any):bretingic

Exception in Tkinter callback
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.12/tkinter/__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/data/user/0/com.termux/files/home/selenium/main.py", line 57, in <lambda>
    submit_button = tk.Button(root, text="Submit", command= lambda: self.save_link(entry_user_email,entry_user_password,entry_user_link))
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.termux/files/home/selenium/main.py", line 76, in save_link
    TestParser.check_account_link(sb,user_link,user_email,user_password)
  File "/data/user/0/com.termux/files/home/selenium/main.py", line 98, in check_account_link
    self.wait_for_element_visible('[class="HB1eCd-UMrnmb"]') #wait for site load
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/seleniumbase/fixtures/base_case.py", line 8657, in wait_for_element_visible
    return page_actions.wait_for_element_visible(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/seleniumbase/fixtures/page_actions.py", line 494, in wait_for_element_visible
    timeout_exception(NoSuchElementException, message)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/seleniumbase/fixtures/page_actions.py", line 252, in timeout_exception
    raise exc(msg)
seleniumbase.common.exceptions.NoSuchElementException: Message:
 Element {[class="HB1eCd-UMrnmb"]} was not present after 10 seconds!
```

i think it's because class name on div has changed

**Comment by corazonthedev** [comment]
it's probably still about timing, even though parser works with most of forms, some forms create different div's than others, you can check your form manually in real-time to see if div is changing or not
